### PR TITLE
Yzguy/show lldp neighbors

### PR DESCRIPTION
**Pull request by yzguy**
Add module for `show lldp neighbors`

Sample usage
```
	show := module.Show(node)
	lldpInfo := show.ShowLLDPNeighbors()

	fmt.Println(lldpInfo.TablesLastChangeTime)
	fmt.Println(lldpInfo.TablesAgeouts)
	fmt.Println(lldpInfo.TablesInserts)
	fmt.Println(lldpInfo.TablesDeletes)
	fmt.Println(lldpInfo.TablesDrops)
	for _, neighbor := range lldpInfo.LLDPNeighbors {
		fmt.Println(neighbor.NeighborDevice)
	}
```

### CODE REVIEW

**Comment by yzguy** [comment]
I'm working on a test, however I'm not really sure how I get the fixtures file working within the tests so I can run it through the new code and then assert that it loaded/marshalled correctly.

I don't see any tests for other commands like `show version`, `show interfaces`, etc.

Can you provide some guidance on how to test show commands?

**Comment by zlesnr** [comment]
@cheynearista Are you available for review here?  We'd like to start integrating with this code and will likely need to add some bits.  Having good patterns for contributions would be helpful.

Thanks for the great start on this code too!

**Comment by cheynearista** [comment]
@zlesnr The changes look good. In terms of tests, Ideally I need to revisit the testing/mocking structure and possibly refactor using one of the various mocking libs readily available. 

Otherwise, we are left to creating our own DummyConnection type that implements the EapiConnectionEntity interface. In the below *rough* example of lldp_test.go I show how you can do that. Granted, it's not the prettiest, but it will at least verify the data is being Unmarshalled correctly. I've also included the json fixture.

I'll look more into how we can improve this. I'm also open to ideas :)

```
package module

import (
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"testing"

	"github.com/aristanetworks/goeapi"
)

type DummyConnection struct {
	goeapi.EapiConnection
	err error
}

func (conn *DummyConnection) Execute(commands []interface{},
	encoding string) (*goeapi.JSONRPCResponse, error) {

	if encoding != "json" {
		return nil, fmt.Errorf("%s encoding not implemented", encoding)
	}

	if conn.err != nil {
		conn.SetError(conn.err)
		return &goeapi.JSONRPCResponse{}, conn.err
	}
        // command 0: enable
        // command 1: show lldp neighbors
	cmd := commands[1].(string)
	fixtureName := strings.Replace(cmd, " ", "_", -1) + ".json"
	// cmd: 'show lldp neighbors' will cause us to look for
	// fixture 'show-lldp-neighbors.json'
	r, err := os.Open(GetFixture(fixtureName))
	if err != nil {
		return nil, fmt.Errorf("Error opening fixture: %s", err)
	}
	defer r.Close()
	return conn.decodeJSONFile(r), nil
}

func (conn *DummyConnection) SetTimeout(uint32) {
}

func (conn *DummyConnection) Error() error {
	return conn.err
}

func (conn *DummyConnection) decodeJSONFile(r io.Reader) *goeapi.JSONRPCResponse {
	dec := json.NewDecoder(r)
	var v goeapi.JSONRPCResponse
	if err := dec.Decode(&v); err != nil {
		panic(err)
	}
	return &v
}

func TestShowLLDPNeighbors_UnitTest(t *testing.T) {
	var dummyNode *goeapi.Node
	var dummyConnection *DummyConnection

	dummyConnection = &DummyConnection{}

	dummyNode = &goeapi.Node{}
	dummyNode.SetConnection(dummyConnection)

	show := Show(dummyNode)
	neighbors := show.ShowLLDPNeighbors()

	fmt.Printf("%+v", neighbors)
}
```

testdata/fixtures/show_lldp_neighbors.json
```
{
  "jsonrpc": "2.0",
  "id": "1",
  "result": [
    {},
    {
      "tablesLastChangeTime": 1525725499.1374352,
      "tablesAgeOuts": 0,
      "tablesInserts": 5,
      "lldpNeighbors": [
        {
          "ttl": 120,
          "neighborDevice": "testsw1.aristanetworks.com",
          "neighborPort": "Ethernet48",
          "port": "Ethernet3"
        },
        {
          "ttl": 120,
          "neighborDevice": "testsw1.aristanetworks.com",
          "neighborPort": "Ethernet47",
          "port": "Ethernet4"
        },
        {
          "ttl": 120,
          "neighborDevice": "testsw1.aristanetworks.com",
          "neighborPort": "Ethernet14",
          "port": "Ethernet14"
        },
        {
          "ttl": 120,
          "neighborDevice": "testsw1.aristanetworks.com",
          "neighborPort": "Ethernet33",
          "port": "Management1"
        }
      ],
      "tablesDeletes": 1,
      "tablesDrops": 0
    }
  ]
}
```

**Comment by yzguy** [comment]
I pulled in your rough code and added more to the test.

One thing I noticed is that the fixtures file has a `{},`, which does not seem to show up in the API explorer, when I try to remove it I get the following error

```
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 109 [running]:
testing.tRunner.func1(0xc4200a4960)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:711 +0x2d2
panic(0x133ef80, 0x1572f40)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/panic.go:491 +0x283
github.com/aristanetworks/goeapi/module.TestShowLLDPNeighbors_UnitTest(0xc4200a4960)
	/Users/asmith/Projects/golang/src/github.com/aristanetworks/goeapi/module/lldp_test.go:102 +0x5f2
testing.tRunner(0xc4200a4960, 0x13bcc10)
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:746 +0xd0
created by testing.(*T).Run
	/usr/local/Cellar/go/1.9.3/libexec/src/testing/testing.go:789 +0x2de
FAIL	github.com/aristanetworks/goeapi/module	0.145s
godep: go exit status 1
make: *** [unittest] Error 1
```

**Comment by yzguy** [comment]
Oh this bit is what is happening. Makes sense now.

```
        // command 0: enable
        // command 1: show lldp neighbors
	cmd := commands[1].(string)
```

Thank you for your help!

**Pull request merged**
